### ISSUE TITLE
Bug in BoundlessRotatedSpaceIntervention

### ISSUE THREAD

**Issue by jiudingsun01** [stanfordnlp/pyvene#73]
In the new version, self.embed_dim in line 262 in interventions.py is initialized as None and never assigned value. This will cause the failure of running Doundless_DAS.ipynb:

Traceback (most recent call last):
  File "/work/frink/sun.jiu/function_vectors/src/compute_rotational_subspace.py", line 300, in <module>
    intervenable = IntervenableModel(intervenable_config, model)
  File "/work/frink/sun.jiu/miniconda3/envs/fv/lib/python3.10/site-packages/pyvene/models/intervenable_base.py", line 111, in __init__
    intervention = intervention_function(
  File "/work/frink/sun.jiu/miniconda3/envs/fv/lib/python3.10/site-packages/pyvene/models/interventions.py", line 265, in __init__
    torch.arange(0, self.embed_dim), requires_grad=False
TypeError: arange() received an invalid combination of arguments - got (int, NoneType), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * 

Simply changing the line into:

self.embed_dim = embed_dim

Would solve the issue.

**Comment by jiudingsun01** [comment]
Issue already fixed. I was running under a previous version. Sorry about the confusion.
